@baseUrl = http://localhost:3000 

###RECADOS
GET {{baseUrl}}/recados/
#?limit=10
#&offset=10
#&user=filipe

###Lista apenas um recado
GET {{baseUrl}}/recados/2/

### Cria um recado
POST  {{baseUrl}}/recados/
Content-Type: application/json

{
    "texto": "NOVO recado",
    "de": "Joana",
    "para": "Joao"
  }

#### Atualiza um recado
PATCH  {{baseUrl}}/recados/3/
Content-Type: application/json

{
    "texto": "ou meu deus o que eu fiz"
}

### Apaga um recado
DELETE {{baseUrl}}/recados/1/