@baseUrl = http://localhost:3000 

###RECADOS
GET {{baseUrl}}/recados/
?limit=5
&offset=0
Authorization: Bearer 123456

###Lista apenas um recado
GET {{baseUrl}}/recados/23/

### Cria um recado
POST  {{baseUrl}}/recados/
Content-Type: application/json

  {
    "texto": "NOVO recado",
    "deId": 10,
    "paraId": 8
  }

#### Atualiza um recado
PATCH  {{baseUrl}}/recados/11/
Content-Type: application/json

{
   "texto": "Bla bla",
   "lido": true
}

### Apaga um recado
DELETE {{baseUrl}}/recados/23/


#####################################################################

##Pessoas
GET {{baseUrl}}/pessoas/
#?limit=10
#&offset=10
#&user=filipe
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjE0LCJlbWFpbCI6ImZpbGlwZS5qeC4xMEBnbWFpbC5jb20iLCJpYXQiOjE3Mjk2MDkyMzIsImV4cCI6MTcyOTYxMjgzMiwiYXVkIjoiaHR0cDovL2xvY2FsaG9zdDozMDAwIiwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDozMDAwIn0.MramppvWjIBZ7wN0oDqCe1VGeW_gNuad87Kp5F4ZibM

###Lista apenas uma pessoa
GET {{baseUrl}}/pessoas/12/

### Cria uma pessoa
POST  {{baseUrl}}/pessoas/
Content-Type: application/json

  {
   "email": "filipe.jx.10@gmail.com",
   "password": "123456",
   "nome": "Filipe Oliveira"
  }

#### Atualiza um recado
PATCH  {{baseUrl}}/pessoas/12/
Content-Type: application/json

{
    "password": "senha1234"
}

### Apaga um recado
DELETE {{baseUrl}}/pessoas/1/


#####################################################################

## AUTH
POST {{baseUrl}}/auth
Content-Type: application/json

  {
    "email": "filipe.jx.10@gmail.com",
    "password": "123456"
  }
 



